#Based on postgres image
FROM postgres:11.6-alpine

#port
EXPOSE 5432

#copy sql scripts to init db
COPY 01-CreateScheme.sql /docker-entrypoint-initdb.d
COPY 02-InsertData.sql /docker-entrypoint-initdb.d

#Env variables
ENV POSTGRES_DB=db \
POSTGRES_USER=usr \
POSTGRES_PASSWORD=pwd